const LINGARAJA_PRODUCTS = {
  BULL: [
    {
      sku: "03038129",
      hs: "8467295100",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "230mm 2400W",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "BULL Angle Grinder 230mm 2400W",
    },
    {
      sku: "329010",
      hs: "8467295100",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "100mm 750W",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "BULL Angle Grinder 100mm 750W",
    },
    {
      sku: "1333511",
      hs: "8467295100",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "180mm 2000W",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "BULL Angle Grinder 180mm 2000W",
    },
    {
      sku: "1333513",
      hs: "8467295100",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "230mm 2400W",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "BULL Angle Grinder 230mm 2400W",
    },
    {
      sku: "1333485",
      hs: "8467295100",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "125mm 900W",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "BULL Angle Grinder 125mm 900W",
    },
    {
      sku: "03017126",
      hs: "8467295100",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "115mm 850W",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "BULL Angle Grinder 115mm 850W",
    },
    {
      sku: "07018126",
      hs: "8467223000",
      type: "Circular Saw",
      icon: "saw",
      spec: "254mm Petrol 52cc",
      desc: "High-torque blade drive engineered for clean, fast cuts under load.",
      name: "BULL Circular Saw 254mm Petrol 52cc",
    },
    {
      sku: "0325265",
      hs: "8461509009",
      type: "Metal Cutting Machine",
      icon: "machine",
      spec: "Bench 250mm",
      desc: "Rigid cast base and industrial-grade bearings for high-accuracy work.",
      name: "BULL Metal Cutting Machine Bench 250mm",
    },
    {
      sku: "0329190",
      hs: "8467298509",
      type: "Multi-Purpose Power Tool",
      icon: "drill",
      spec: "SDS-Plus 26mm 900W",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "BULL Multi-Purpose Power Tool SDS-Plus 26mm 900W",
    },
    {
      sku: "10008225",
      hs: "8467298509",
      type: "Multi-Purpose Power Tool",
      icon: "drill",
      spec: "SDS-Plus 26mm 900W",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "BULL Multi-Purpose Power Tool SDS-Plus 26mm 900W",
    },
    {
      sku: "0329022",
      hs: "8467297000",
      type: "Cordless Impact Driver",
      icon: "drill",
      spec: "SDS-Plus 26mm 900W",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "BULL Cordless Impact Driver SDS-Plus 26mm 900W",
    },
    {
      sku: "17033129",
      hs: "8467297000",
      type: "Cordless Impact Driver",
      icon: "drill",
      spec: "SDS-Plus 26mm 900W",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "BULL Cordless Impact Driver SDS-Plus 26mm 900W",
    },
    {
      sku: "16031326",
      hs: "8516797000",
      type: "Heat Gun",
      icon: "heatgun",
      spec: "2000W Dual Speed",
      desc: "Adjustable dual-temperature control for surface prep and forming tasks.",
      name: "BULL Heat Gun 2000W Dual Speed",
    },
    {
      sku: "1327422",
      hs: "8467219900",
      type: "Impact Drill",
      icon: "drill",
      spec: "13mm 650W",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "BULL Impact Drill 13mm 650W",
    },
    {
      sku: "20046329",
      hs: "8467229000",
      type: "Reciprocating Saw",
      icon: "saw",
      spec: "210mm 2000W Circular",
      desc: "High-torque blade drive engineered for clean, fast cuts under load.",
      name: "BULL Reciprocating Saw 210mm 2000W Circular",
    },
    {
      sku: "0325361",
      hs: "8465912000",
      type: "Wood Planer",
      icon: "saw",
      spec: "185mm 1400W",
      desc: "High-torque blade drive engineered for clean, fast cuts under load.",
      name: "BULL Wood Planer 185mm 1400W",
    },
    {
      sku: "0327338",
      hs: "8467295900",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "150mm 1200W",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "BULL Angle Grinder 150mm 1200W",
    },
    {
      sku: "0319102",
      hs: "8467298509",
      type: "Multi-Purpose Power Tool",
      icon: "drill",
      spec: "13mm 650W",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "BULL Multi-Purpose Power Tool 13mm 650W",
    },
    {
      sku: "01045325",
      hs: "8467219100",
      type: "Impact Drill",
      icon: "drill",
      spec: "13mm 650W",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "BULL Impact Drill 13mm 650W",
    },
    {
      sku: "0329082",
      hs: "8467219100",
      type: "Impact Drill",
      icon: "drill",
      spec: "16mm 750W VSR",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "BULL Impact Drill 16mm 750W VSR",
    },
    {
      sku: "1333409",
      hs: "8467219900",
      type: "Impact Drill",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "BULL Impact Drill — SKU 1333409",
    },
    {
      sku: "0304362",
      hs: "8467298509",
      type: "Multi-Purpose Power Tool",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "BULL Multi-Purpose Power Tool — SKU 0304362",
    },
    {
      sku: "15030129",
      hs: "8508190001",
      type: "Vacuum Cleaner Accessory",
      icon: "vacuum",
      spec: "Contact sales desk for full spec sheet",
      desc: "Genuine replacement accessory engineered for consistent fit and suction.",
      name: "BULL Vacuum Cleaner Accessory — SKU 15030129",
    },
    {
      sku: "1329490",
      hs: "8508190001",
      type: "Vacuum Cleaner Accessory",
      icon: "vacuum",
      spec: "Contact sales desk for full spec sheet",
      desc: "Genuine replacement accessory engineered for consistent fit and suction.",
      name: "BULL Vacuum Cleaner Accessory — SKU 1329490",
    },
    {
      sku: "12043525",
      hs: "8467298509",
      type: "Multi-Purpose Power Tool",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "BULL Multi-Purpose Power Tool — SKU 12043525",
    },
    {
      sku: "1304755",
      hs: "8424890009",
      type: "Airless Paint Sprayer",
      icon: "heatgun",
      spec: "Contact sales desk for full spec sheet",
      desc: "Consistent atomisation and adjustable flow for fast, even site coverage.",
      name: "BULL Airless Paint Sprayer — SKU 1304755",
    },
    {
      sku: "1327639",
      hs: "8467295100",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "Contact sales desk for full spec sheet",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "BULL Angle Grinder — SKU 1327639",
    },
    {
      sku: "1333515",
      hs: "8467295100",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "Contact sales desk for full spec sheet",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "BULL Angle Grinder — SKU 1333515",
    },
    {
      sku: "1333516",
      hs: "8467295100",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "Contact sales desk for full spec sheet",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "BULL Angle Grinder — SKU 1333516",
    },
    {
      sku: "1333622",
      hs: "8467295100",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "Contact sales desk for full spec sheet",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "BULL Angle Grinder — SKU 1333622",
    },
    {
      sku: "1304557",
      hs: "8467295900",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "Contact sales desk for full spec sheet",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "BULL Angle Grinder — SKU 1304557",
    },
    {
      sku: "1329950",
      hs: "8716800000",
      type: "Site Hand Trolley",
      icon: "machine",
      spec: "Contact sales desk for full spec sheet",
      desc: "Reinforced frame and wheels built to move heavy loads around site.",
      name: "BULL Site Hand Trolley — SKU 1329950",
    },
    {
      sku: "1329815",
      hs: "8467219100",
      type: "Impact Drill",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "BULL Impact Drill — SKU 1329815",
    },
    {
      sku: "1325783",
      hs: "8467219100",
      type: "Impact Drill",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "BULL Impact Drill — SKU 1325783",
    },
    {
      sku: "1329605",
      hs: "8467298509",
      type: "Multi-Purpose Power Tool",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "BULL Multi-Purpose Power Tool — SKU 1329605",
    },
  ],
  ECO: [
    {
      sku: "SGK-5",
      hs: "8481809907",
      type: "Ball Valve",
      icon: "valve",
      spec: "DN50 PN16",
      desc: "Corrosion-resistant body rated for continuous industrial flow control.",
      name: "ECO Ball Valve DN50 PN16",
    },
    {
      sku: "AE-10-OF1",
      hs: "8414802200",
      type: "Air Compressor",
      icon: "compressor",
      spec: "Twin Cylinder 5HP",
      desc: "Low-noise pump with thermal overload protection for long duty cycles.",
      name: "ECO Air Compressor Twin Cylinder 5HP",
    },
    {
      sku: "AE-1005-B2",
      hs: "8414802200",
      type: "Air Compressor",
      icon: "compressor",
      spec: "50L 2HP",
      desc: "Low-noise pump with thermal overload protection for long duty cycles.",
      name: "ECO Air Compressor 50L 2HP",
    },
    {
      sku: "AE-251-4",
      hs: "8414802200",
      type: "Air Compressor",
      icon: "compressor",
      spec: "100L 3HP Silent",
      desc: "Low-noise pump with thermal overload protection for long duty cycles.",
      name: "ECO Air Compressor 100L 3HP Silent",
    },
    {
      sku: "AE-501-3",
      hs: "8414802200",
      type: "Air Compressor",
      icon: "compressor",
      spec: "50L 2HP",
      desc: "Low-noise pump with thermal overload protection for long duty cycles.",
      name: "ECO Air Compressor 50L 2HP",
    },
    {
      sku: "AE-501-4",
      hs: "8414802200",
      type: "Air Compressor",
      icon: "compressor",
      spec: "Twin Cylinder 5HP",
      desc: "Low-noise pump with thermal overload protection for long duty cycles.",
      name: "ECO Air Compressor Twin Cylinder 5HP",
    },
    {
      sku: "AIW-610",
      hs: "8467119000",
      type: "Electric Drill",
      icon: "drill",
      spec: "16mm 750W VSR",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "ECO Electric Drill 16mm 750W VSR",
    },
    {
      sku: "ASL-40B",
      hs: "8467190000",
      type: "Electric Screwdriver",
      icon: "drill",
      spec: "10mm 500W",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "ECO Electric Screwdriver 10mm 500W",
    },
    {
      sku: "GFI-1203",
      hs: "8413708100",
      type: "Centrifugal Water Pump",
      icon: "pump",
      spec: "0.5HP Self-Priming",
      desc: "Self-priming design with sealed bearings for reliable water transfer.",
      name: "ECO Centrifugal Water Pump 0.5HP Self-Priming",
    },
    {
      sku: "EC1512-9",
      hs: "8467890000",
      type: "Pneumatic Air Tool",
      icon: "compressor",
      spec: "50L 2HP",
      desc: "Low-noise pump with thermal overload protection for long duty cycles.",
      name: "ECO Pneumatic Air Tool 50L 2HP",
    },
    {
      sku: "EC1515-3",
      hs: "8467890000",
      type: "Pneumatic Air Tool",
      icon: "compressor",
      spec: "50L 2HP",
      desc: "Low-noise pump with thermal overload protection for long duty cycles.",
      name: "ECO Pneumatic Air Tool 50L 2HP",
    },
    {
      sku: "EC1550-4",
      hs: "8467890000",
      type: "Pneumatic Air Tool",
      icon: "compressor",
      spec: "50L 2HP",
      desc: "Low-noise pump with thermal overload protection for long duty cycles.",
      name: "ECO Pneumatic Air Tool 50L 2HP",
    },
    {
      sku: "EC1551-5",
      hs: "8467890000",
      type: "Pneumatic Air Tool",
      icon: "compressor",
      spec: "24L Oil-Free 1.5HP",
      desc: "Low-noise pump with thermal overload protection for long duty cycles.",
      name: "ECO Pneumatic Air Tool 24L Oil-Free 1.5HP",
    },
    {
      sku: "GTP-B25",
      hs: "6307909800",
      type: "Heavy-Duty Work Gloves",
      icon: "glove",
      spec: "Size XL Nitrile Coated",
      desc: "Reinforced palm construction for grip and abrasion resistance on site.",
      name: "ECO Heavy-Duty Work Gloves Size XL Nitrile Coated",
    },
    {
      sku: "CSP-265",
      hs: "8467810000",
      type: "Petrol Chainsaw",
      icon: "saw",
      spec: "190mm 1600W",
      desc: "High-torque blade drive engineered for clean, fast cuts under load.",
      name: "ECO Petrol Chainsaw 190mm 1600W",
    },
    {
      sku: "GFI-07P",
      hs: "8413708100",
      type: "Centrifugal Water Pump",
      icon: "pump",
      spec: "0.5HP Self-Priming",
      desc: "Self-priming design with sealed bearings for reliable water transfer.",
      name: "ECO Centrifugal Water Pump 0.5HP Self-Priming",
    },
    {
      sku: "GFI-13P",
      hs: "8413708100",
      type: "Centrifugal Water Pump",
      icon: "pump",
      spec: "0.5HP Self-Priming",
      desc: "Self-priming design with sealed bearings for reliable water transfer.",
      name: "ECO Centrifugal Water Pump 0.5HP Self-Priming",
    },
    {
      sku: "PE-4001RS",
      hs: "8502202000",
      type: "Portable Generator Set",
      icon: "compressor",
      spec: "Twin Cylinder 5HP",
      desc: "Low-noise pump with thermal overload protection for long duty cycles.",
      name: "ECO Portable Generator Set Twin Cylinder 5HP",
    },
    {
      sku: "PE-7001RS",
      hs: "8502202000",
      type: "Portable Generator Set",
      icon: "compressor",
      spec: "50L 2HP",
      desc: "Low-noise pump with thermal overload protection for long duty cycles.",
      name: "ECO Portable Generator Set 50L 2HP",
    },
    {
      sku: "PE-9001E3FP",
      hs: "8502202000",
      type: "Portable Generator Set",
      icon: "compressor",
      spec: "100L 3HP Silent",
      desc: "Low-noise pump with thermal overload protection for long duty cycles.",
      name: "ECO Portable Generator Set 100L 3HP Silent",
    },
    {
      sku: "LG-735",
      hs: "8433115900",
      type: "Lawn Mower / Brush Cutter",
      icon: "saw",
      spec: "Contact sales desk for full spec sheet",
      desc: "Engineered cutting deck and drive for efficient lawn and vegetation clearing.",
      name: "ECO Lawn Mower / Brush Cutter — SKU LG-735",
    },
    {
      sku: "EC3410-2",
      hs: "8433119000",
      type: "Lawn Mower / Brush Cutter",
      icon: "saw",
      spec: "Contact sales desk for full spec sheet",
      desc: "Engineered cutting deck and drive for efficient lawn and vegetation clearing.",
      name: "ECO Lawn Mower / Brush Cutter — SKU EC3410-2",
    },
    {
      sku: "EC1553-7",
      hs: "8433119000",
      type: "Lawn Mower / Brush Cutter",
      icon: "saw",
      spec: "Contact sales desk for full spec sheet",
      desc: "Engineered cutting deck and drive for efficient lawn and vegetation clearing.",
      name: "ECO Lawn Mower / Brush Cutter — SKU EC1553-7",
    },
    {
      sku: "WP-1404D",
      hs: "8413708100",
      type: "Centrifugal Water Pump",
      icon: "pump",
      spec: "Contact sales desk for full spec sheet",
      desc: "Self-priming design with sealed bearings for reliable water transfer.",
      name: "ECO Centrifugal Water Pump — SKU WP-1404D",
    },
    {
      sku: "WP-153C",
      hs: "8413708100",
      type: "Centrifugal Water Pump",
      icon: "pump",
      spec: "Contact sales desk for full spec sheet",
      desc: "Self-priming design with sealed bearings for reliable water transfer.",
      name: "ECO Centrifugal Water Pump — SKU WP-153C",
    },
    {
      sku: "EC2012-1",
      hs: "8413708100",
      type: "Centrifugal Water Pump",
      icon: "pump",
      spec: "Contact sales desk for full spec sheet",
      desc: "Self-priming design with sealed bearings for reliable water transfer.",
      name: "ECO Centrifugal Water Pump — SKU EC2012-1",
    },
    {
      sku: "EC4910-1",
      hs: "8424300800",
      type: "High-Pressure Washer",
      icon: "compressor",
      spec: "Contact sales desk for full spec sheet",
      desc: "High-pressure pump unit for fast, effective surface and vehicle cleaning.",
      name: "ECO High-Pressure Washer — SKU EC4910-1",
    },
    {
      sku: "HPW1825RSE01",
      hs: "8424300800",
      type: "High-Pressure Washer",
      icon: "compressor",
      spec: "Contact sales desk for full spec sheet",
      desc: "High-pressure pump unit for fast, effective surface and vehicle cleaning.",
      name: "ECO High-Pressure Washer — SKU HPW1825RSE01",
    },
    {
      sku: "ASP11-150",
      hs: "8467119000",
      type: "Electric Drill",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "ECO Electric Drill — SKU ASP11-150",
    },
    {
      sku: "ASP12-150V",
      hs: "8467119000",
      type: "Electric Drill",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "ECO Electric Drill — SKU ASP12-150V",
    },
    {
      sku: "AHE-0560",
      hs: "3917390008",
      type: "Reinforced Hose",
      icon: "pump",
      spec: "Contact sales desk for full spec sheet",
      desc: "Reinforced hose engineered for consistent flow and long service life on site.",
      name: "ECO Reinforced Hose — SKU AHE-0560",
    },
    {
      sku: "TIG-2",
      hs: "8481807900",
      type: "Industrial Valve",
      icon: "valve",
      spec: "Contact sales desk for full spec sheet",
      desc: "Corrosion-resistant body rated for continuous industrial flow control.",
      name: "ECO Industrial Valve — SKU TIG-2",
    },
    {
      sku: "EC3924-3",
      hs: "8424200000",
      type: "Spray Gun",
      icon: "heatgun",
      spec: "Contact sales desk for full spec sheet",
      desc: "Adjustable nozzle and flow control for coatings, paints and finishes.",
      name: "ECO Spray Gun — SKU EC3924-3",
    },
    {
      sku: "EC3924-4",
      hs: "8424200000",
      type: "Spray Gun",
      icon: "heatgun",
      spec: "Contact sales desk for full spec sheet",
      desc: "Adjustable nozzle and flow control for coatings, paints and finishes.",
      name: "ECO Spray Gun — SKU EC3924-4",
    },
    {
      sku: "EC3924-1",
      hs: "3917390008",
      type: "Reinforced Hose",
      icon: "pump",
      spec: "Contact sales desk for full spec sheet",
      desc: "Reinforced hose engineered for consistent flow and long service life on site.",
      name: "ECO Reinforced Hose — SKU EC3924-1",
    },
    {
      sku: "ASB-06S",
      hs: "8424301000",
      type: "High-Pressure Washer",
      icon: "compressor",
      spec: "Contact sales desk for full spec sheet",
      desc: "High-pressure pump unit for fast, effective surface and vehicle cleaning.",
      name: "ECO High-Pressure Washer — SKU ASB-06S",
    },
    {
      sku: "SG-1000H15U",
      hs: "8424200000",
      type: "Spray Gun",
      icon: "heatgun",
      spec: "Contact sales desk for full spec sheet",
      desc: "Adjustable nozzle and flow control for coatings, paints and finishes.",
      name: "ECO Spray Gun — SKU SG-1000H15U",
    },
    {
      sku: "EC1533-17",
      hs: "8424200000",
      type: "Spray Gun",
      icon: "heatgun",
      spec: "Contact sales desk for full spec sheet",
      desc: "Adjustable nozzle and flow control for coatings, paints and finishes.",
      name: "ECO Spray Gun — SKU EC1533-17",
    },
    {
      sku: "EC1534-14",
      hs: "8424200000",
      type: "Spray Gun",
      icon: "heatgun",
      spec: "Contact sales desk for full spec sheet",
      desc: "Adjustable nozzle and flow control for coatings, paints and finishes.",
      name: "ECO Spray Gun — SKU EC1534-14",
    },
    {
      sku: "EC3010-2",
      hs: "8414802200",
      type: "Air Compressor",
      icon: "compressor",
      spec: "Contact sales desk for full spec sheet",
      desc: "Low-noise pump with thermal overload protection for long duty cycles.",
      name: "ECO Air Compressor — SKU EC3010-2",
    },
    {
      sku: "AE-013-4",
      hs: "8414802200",
      type: "Air Compressor",
      icon: "compressor",
      spec: "Contact sales desk for full spec sheet",
      desc: "Low-noise pump with thermal overload protection for long duty cycles.",
      name: "ECO Air Compressor — SKU AE-013-4",
    },
    {
      sku: "AE-016-1",
      hs: "8414802200",
      type: "Air Compressor",
      icon: "compressor",
      spec: "Contact sales desk for full spec sheet",
      desc: "Low-noise pump with thermal overload protection for long duty cycles.",
      name: "ECO Air Compressor — SKU AE-016-1",
    },
  ],
  WORTEX: [
    {
      sku: "0333292",
      hs: "8467295100",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "100mm 750W",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "WORTEX Angle Grinder 100mm 750W",
    },
    {
      sku: "0329155",
      hs: "8467295100",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "100mm 750W",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "WORTEX Angle Grinder 100mm 750W",
    },
    {
      sku: "AG1210100013",
      hs: "8467295100",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "150mm 1200W",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "WORTEX Angle Grinder 150mm 1200W",
    },
    {
      sku: "AG12111E0018",
      hs: "8467295100",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "125mm 900W",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "WORTEX Angle Grinder 125mm 900W",
    },
    {
      sku: "AG121300018",
      hs: "8467295100",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "230mm 2400W",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "WORTEX Angle Grinder 230mm 2400W",
    },
    {
      sku: "AG12133E00013",
      hs: "8467295100",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "115mm 850W",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "WORTEX Angle Grinder 115mm 850W",
    },
    {
      sku: "0325104",
      hs: "8465930000",
      type: "Orbital Sander",
      icon: "saw",
      spec: "185mm 1400W",
      desc: "High-torque blade drive engineered for clean, fast cuts under load.",
      name: "WORTEX Orbital Sander 185mm 1400W",
    },
    {
      sku: "1319379",
      hs: "8460390000",
      type: "Bench Grinding Machine",
      icon: "machine",
      spec: "Floor Standing 3HP",
      desc: "Rigid cast base and industrial-grade bearings for high-accuracy work.",
      name: "WORTEX Bench Grinding Machine Floor Standing 3HP",
    },
    {
      sku: "CS161200019",
      hs: "8467223000",
      type: "Circular Saw",
      icon: "saw",
      spec: "210mm 2000W Circular",
      desc: "High-torque blade drive engineered for clean, fast cuts under load.",
      name: "WORTEX Circular Saw 210mm 2000W Circular",
    },
    {
      sku: "1333550",
      hs: "8467223000",
      type: "Circular Saw",
      icon: "saw",
      spec: "190mm 1600W",
      desc: "High-torque blade drive engineered for clean, fast cuts under load.",
      name: "WORTEX Circular Saw 190mm 1600W",
    },
    {
      sku: "CS191500019",
      hs: "8467223000",
      type: "Circular Saw",
      icon: "saw",
      spec: "210mm 2000W Circular",
      desc: "High-torque blade drive engineered for clean, fast cuts under load.",
      name: "WORTEX Circular Saw 210mm 2000W Circular",
    },
    {
      sku: "CS1916L00021",
      hs: "8467223000",
      type: "Circular Saw",
      icon: "saw",
      spec: "190mm 1600W",
      desc: "High-torque blade drive engineered for clean, fast cuts under load.",
      name: "WORTEX Circular Saw 190mm 1600W",
    },
    {
      sku: "1333556",
      hs: "8467223000",
      type: "Circular Saw",
      icon: "saw",
      spec: "Orbital 240W",
      desc: "High-torque blade drive engineered for clean, fast cuts under load.",
      name: "WORTEX Circular Saw Orbital 240W",
    },
    {
      sku: "1318793",
      hs: "8467219900",
      type: "Impact Drill",
      icon: "drill",
      spec: "16mm 750W VSR",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "WORTEX Impact Drill 16mm 750W VSR",
    },
    {
      sku: "0334331",
      hs: "8467219900",
      type: "Impact Drill",
      icon: "drill",
      spec: "10mm 500W",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "WORTEX Impact Drill 10mm 500W",
    },
    {
      sku: "0329269",
      hs: "8467292000",
      type: "Straight Grinder",
      icon: "grinder",
      spec: "150mm 1200W",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "WORTEX Straight Grinder 150mm 1200W",
    },
    {
      sku: "0329202",
      hs: "8467292000",
      type: "Straight Grinder",
      icon: "grinder",
      spec: "150mm 1200W",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "WORTEX Straight Grinder 150mm 1200W",
    },
    {
      sku: "1334781",
      hs: "8467292000",
      type: "Straight Grinder",
      icon: "grinder",
      spec: "180mm 2000W",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "WORTEX Straight Grinder 180mm 2000W",
    },
    {
      sku: "1329459",
      hs: "8465912000",
      type: "Wood Planer",
      icon: "saw",
      spec: "190mm 1600W",
      desc: "High-torque blade drive engineered for clean, fast cuts under load.",
      name: "WORTEX Wood Planer 190mm 1600W",
    },
    {
      sku: "AS350100025",
      hs: "8461509009",
      type: "Metal Cutting Machine",
      icon: "machine",
      spec: "Bench 250mm",
      desc: "Rigid cast base and industrial-grade bearings for high-accuracy work.",
      name: "WORTEX Metal Cutting Machine Bench 250mm",
    },
    {
      sku: "1333509",
      hs: "8467298509",
      type: "Multi-Purpose Power Tool",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "WORTEX Multi-Purpose Power Tool — SKU 1333509",
    },
    {
      sku: "JS7008LE019",
      hs: "8467229000",
      type: "Reciprocating Saw",
      icon: "saw",
      spec: "Contact sales desk for full spec sheet",
      desc: "High-torque blade drive engineered for clean, fast cuts under load.",
      name: "WORTEX Reciprocating Saw — SKU JS7008LE019",
    },
    {
      sku: "0325116",
      hs: "8467229000",
      type: "Reciprocating Saw",
      icon: "saw",
      spec: "Contact sales desk for full spec sheet",
      desc: "High-torque blade drive engineered for clean, fast cuts under load.",
      name: "WORTEX Reciprocating Saw — SKU 0325116",
    },
    {
      sku: "0319212",
      hs: "8467229000",
      type: "Reciprocating Saw",
      icon: "saw",
      spec: "Contact sales desk for full spec sheet",
      desc: "High-torque blade drive engineered for clean, fast cuts under load.",
      name: "WORTEX Reciprocating Saw — SKU 0319212",
    },
    {
      sku: "1330427",
      hs: "8467298509",
      type: "Multi-Purpose Power Tool",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "WORTEX Multi-Purpose Power Tool — SKU 1330427",
    },
    {
      sku: "0329088",
      hs: "8467297000",
      type: "Cordless Impact Driver",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "WORTEX Cordless Impact Driver — SKU 0329088",
    },
    {
      sku: "PL200700022",
      hs: "8467297000",
      type: "Cordless Impact Driver",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "WORTEX Cordless Impact Driver — SKU PL200700022",
    },
    {
      sku: "ETAM3203018",
      hs: "8207709000",
      type: "Milling / Cutting Bits",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision-ground cutting bits engineered for clean, consistent material removal.",
      name: "WORTEX Milling / Cutting Bits — SKU ETAM3203018",
    },
    {
      sku: "0323085",
      hs: "8716800000",
      type: "Site Hand Trolley",
      icon: "machine",
      spec: "Contact sales desk for full spec sheet",
      desc: "Reinforced frame and wheels built to move heavy loads around site.",
      name: "WORTEX Site Hand Trolley — SKU 0323085",
    },
    {
      sku: "0334327",
      hs: "8516797000",
      type: "Heat Gun",
      icon: "heatgun",
      spec: "Contact sales desk for full spec sheet",
      desc: "Adjustable dual-temperature control for surface prep and forming tasks.",
      name: "WORTEX Heat Gun — SKU 0334327",
    },
    {
      sku: "DS130620019",
      hs: "8467219900",
      type: "Impact Drill",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "WORTEX Impact Drill — SKU DS130620019",
    },
    {
      sku: "1325477",
      hs: "8467219900",
      type: "Impact Drill",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "WORTEX Impact Drill — SKU 1325477",
    },
    {
      sku: "DS160910025",
      hs: "8467219900",
      type: "Impact Drill",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "WORTEX Impact Drill — SKU DS160910025",
    },
    {
      sku: "0329323",
      hs: "8465912000",
      type: "Wood Planer",
      icon: "saw",
      spec: "Contact sales desk for full spec sheet",
      desc: "High-torque blade drive engineered for clean, fast cuts under load.",
      name: "WORTEX Wood Planer — SKU 0329323",
    },
    {
      sku: "0329126",
      hs: "8465912000",
      type: "Wood Planer",
      icon: "saw",
      spec: "Contact sales desk for full spec sheet",
      desc: "High-torque blade drive engineered for clean, fast cuts under load.",
      name: "WORTEX Wood Planer — SKU 0329126",
    },
    {
      sku: "0329127",
      hs: "8465912000",
      type: "Wood Planer",
      icon: "saw",
      spec: "Contact sales desk for full spec sheet",
      desc: "High-torque blade drive engineered for clean, fast cuts under load.",
      name: "WORTEX Wood Planer — SKU 0329127",
    },
    {
      sku: "MX1416D0330",
      hs: "8467298509",
      type: "Multi-Purpose Power Tool",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "WORTEX Multi-Purpose Power Tool — SKU MX1416D0330",
    },
    {
      sku: "1318467",
      hs: "8467295900",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "Contact sales desk for full spec sheet",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "WORTEX Angle Grinder — SKU 1318467",
    },
    {
      sku: "1318449",
      hs: "8467295900",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "Contact sales desk for full spec sheet",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "WORTEX Angle Grinder — SKU 1318449",
    },
    {
      sku: "PM1813SE0404",
      hs: "8467295900",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "Contact sales desk for full spec sheet",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "WORTEX Angle Grinder — SKU PM1813SE0404",
    },
    {
      sku: "PMW1500PS019",
      hs: "4303900000",
      type: "Lined Winter Work Gloves",
      icon: "glove",
      spec: "Contact sales desk for full spec sheet",
      desc: "Insulated lining with reinforced palm for cold-weather site work.",
      name: "WORTEX Lined Winter Work Gloves — SKU PMW1500PS019",
    },
    {
      sku: "0325118",
      hs: "8467229000",
      type: "Reciprocating Saw",
      icon: "saw",
      spec: "Contact sales desk for full spec sheet",
      desc: "High-torque blade drive engineered for clean, fast cuts under load.",
      name: "WORTEX Reciprocating Saw — SKU 0325118",
    },
    {
      sku: "0329062",
      hs: "8467219100",
      type: "Impact Drill",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "WORTEX Impact Drill — SKU 0329062",
    },
    {
      sku: "RH262901129",
      hs: "8467219100",
      type: "Impact Drill",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "WORTEX Impact Drill — SKU RH262901129",
    },
    {
      sku: "RH282901129",
      hs: "8467219100",
      type: "Impact Drill",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "WORTEX Impact Drill — SKU RH282901129",
    },
    {
      sku: "RH3239F1129",
      hs: "8467219100",
      type: "Impact Drill",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "WORTEX Impact Drill — SKU RH3239F1129",
    },
    {
      sku: "1334497",
      hs: "8716800000",
      type: "Site Hand Trolley",
      icon: "machine",
      spec: "Contact sales desk for full spec sheet",
      desc: "Reinforced frame and wheels built to move heavy loads around site.",
      name: "WORTEX Site Hand Trolley — SKU 1334497",
    },
    {
      sku: "1334426",
      hs: "8467295900",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "Contact sales desk for full spec sheet",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "WORTEX Angle Grinder — SKU 1334426",
    },
    {
      sku: "1334425",
      hs: "8467295900",
      type: "Angle Grinder",
      icon: "grinder",
      spec: "Contact sales desk for full spec sheet",
      desc: "Heavy-duty motor with anti-vibration handle for continuous shop-floor use.",
      name: "WORTEX Angle Grinder — SKU 1334425",
    },
    {
      sku: "1319428",
      hs: "8467223000",
      type: "Circular Saw",
      icon: "saw",
      spec: "Contact sales desk for full spec sheet",
      desc: "High-torque blade drive engineered for clean, fast cuts under load.",
      name: "WORTEX Circular Saw — SKU 1319428",
    },
    {
      sku: "MMB100000018",
      hs: "7325999009",
      type: "Cast Iron Stand / Base",
      icon: "machine",
      spec: "Contact sales desk for full spec sheet",
      desc: "Rigid cast iron construction for stable, vibration-free operation.",
      name: "WORTEX Cast Iron Stand / Base — SKU MMB100000018",
    },
    {
      sku: "1325446",
      hs: "8414802200",
      type: "Air Compressor",
      icon: "compressor",
      spec: "Contact sales desk for full spec sheet",
      desc: "Low-noise pump with thermal overload protection for long duty cycles.",
      name: "WORTEX Air Compressor — SKU 1325446",
    },
    {
      sku: "0323320",
      hs: "4202929800",
      type: "Tool Bag / Case",
      icon: "glove",
      spec: "Contact sales desk for full spec sheet",
      desc: "Durable site bag with reinforced stitching for daily tool transport.",
      name: "WORTEX Tool Bag / Case — SKU 0323320",
    },
    {
      sku: "0323174",
      hs: "4202929800",
      type: "Tool Bag / Case",
      icon: "glove",
      spec: "Contact sales desk for full spec sheet",
      desc: "Durable site bag with reinforced stitching for daily tool transport.",
      name: "WORTEX Tool Bag / Case — SKU 0323174",
    },
    {
      sku: "0323197",
      hs: "4202929800",
      type: "Tool Bag / Case",
      icon: "glove",
      spec: "Contact sales desk for full spec sheet",
      desc: "Durable site bag with reinforced stitching for daily tool transport.",
      name: "WORTEX Tool Bag / Case — SKU 0323197",
    },
    {
      sku: "0323198",
      hs: "4202929800",
      type: "Tool Bag / Case",
      icon: "glove",
      spec: "Contact sales desk for full spec sheet",
      desc: "Durable site bag with reinforced stitching for daily tool transport.",
      name: "WORTEX Tool Bag / Case — SKU 0323198",
    },
    {
      sku: "0323154",
      hs: "9620000005",
      type: "Tripod / Support Stand",
      icon: "machine",
      spec: "Contact sales desk for full spec sheet",
      desc: "Adjustable support stand for stable, accurate instrument positioning.",
      name: "WORTEX Tripod / Support Stand — SKU 0323154",
    },
    {
      sku: "CV201200029",
      hs: "8467298509",
      type: "Multi-Purpose Power Tool",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision gearbox and impact-rated chuck built for daily jobsite demands.",
      name: "WORTEX Multi-Purpose Power Tool — SKU CV201200029",
    },
    {
      sku: "0325363",
      hs: "8508110000",
      type: "Vacuum Cleaner",
      icon: "vacuum",
      spec: "Contact sales desk for full spec sheet",
      desc: "Compact motor unit with strong suction for site clean-up duty.",
      name: "WORTEX Vacuum Cleaner — SKU 0325363",
    },
    {
      sku: "2322023",
      hs: "8460390000",
      type: "Bench Grinding Machine",
      icon: "machine",
      spec: "Contact sales desk for full spec sheet",
      desc: "Rigid cast base and industrial-grade bearings for high-accuracy work.",
      name: "WORTEX Bench Grinding Machine — SKU 2322023",
    },
    {
      sku: "2322025",
      hs: "8460390000",
      type: "Bench Grinding Machine",
      icon: "machine",
      spec: "Contact sales desk for full spec sheet",
      desc: "Rigid cast base and industrial-grade bearings for high-accuracy work.",
      name: "WORTEX Bench Grinding Machine — SKU 2322025",
    },
    {
      sku: "0304339",
      hs: "3926909709",
      type: "Plastic Site Accessory",
      icon: "vacuum",
      spec: "Contact sales desk for full spec sheet",
      desc: "Durable moulded plastic component built for daily site use.",
      name: "WORTEX Plastic Site Accessory — SKU 0304339",
    },
    {
      sku: "1304560",
      hs: "6805100000",
      type: "Abrasive Sheets",
      icon: "saw",
      spec: "Contact sales desk for full spec sheet",
      desc: "Consistent grit distribution for uniform stock removal and finish.",
      name: "WORTEX Abrasive Sheets — SKU 1304560",
    },
    {
      sku: "0323046",
      hs: "8207909900",
      type: "Milling / Cutting Bits",
      icon: "drill",
      spec: "Contact sales desk for full spec sheet",
      desc: "Precision-ground cutting bits engineered for clean, consistent material removal.",
      name: "WORTEX Milling / Cutting Bits — SKU 0323046",
    },
  ],
  ACC: [
    {
      sku: "ACC-OPC43-50",
      hs: "25232990",
      type: "OPC Cement",
      icon: "cement",
      spec: "OPC 43 Grade, 50kg Bag",
      desc: "General-purpose Ordinary Portland Cement for RCC and precast work.",
      name: "ACC OPC 43 Grade Cement 50kg Bag",
    },
    {
      sku: "ACC-OPC53-50",
      hs: "25232990",
      type: "OPC Cement",
      icon: "cement",
      spec: "OPC 53 Grade, 50kg Bag",
      desc: "High early-strength cement suited to structural RCC and prestressed work.",
      name: "ACC OPC 53 Grade Cement 50kg Bag",
    },
    {
      sku: "ACC-PPC-50",
      hs: "25232990",
      type: "PPC Cement",
      icon: "cement",
      spec: "PPC (Fly Ash Based), 50kg Bag",
      desc: "Blended Portland Pozzolana Cement offering finer finish and lower heat of hydration.",
      name: "ACC PPC Cement 50kg Bag",
    },
    {
      sku: "ACC-PSC-50",
      hs: "25232990",
      type: "PSC Cement",
      icon: "cement",
      spec: "Portland Slag Cement, 50kg Bag",
      desc: "Slag-blended cement with high durability, suited to marine and mass concrete work.",
      name: "ACC Portland Slag Cement 50kg Bag",
    },
    {
      sku: "ACC-GOLD-PPC-50",
      hs: "25232990",
      type: "Premium PPC",
      icon: "cement",
      spec: "Gold Premium PPC, 50kg Bag",
      desc: "Premium fine-grind PPC formulated for smoother plaster and superior workability.",
      name: "ACC Gold Premium PPC Cement 50kg Bag",
    },
    {
      sku: "ACC-SURAKSHA-OPC-50",
      hs: "25232990",
      type: "OPC Cement",
      icon: "cement",
      spec: "Suraksha OPC 43, 50kg Bag",
      desc: "Value-tier OPC 43 grade cement for general residential construction.",
      name: "ACC Suraksha OPC 43 Cement 50kg Bag",
    },
    {
      sku: "ACC-F2R-PPC-50",
      hs: "25232990",
      type: "Ready-Mix Grade PPC",
      icon: "cement",
      spec: "F2R PPC, 50kg Bag",
      desc: "PPC engineered for ready-mix and RMC plants requiring consistent flow properties.",
      name: "ACC F2R Ready-Mix Grade PPC 50kg Bag",
    },
    {
      sku: "ACC-OPC43-JUMBO-1250",
      hs: "25232990",
      type: "OPC Cement",
      icon: "cement",
      spec: "OPC 43 Grade, 1250kg Jumbo Bag",
      desc: "Bulk jumbo-bag packaging of OPC 43 grade for large site pours and RMC batching.",
      name: "ACC OPC 43 Grade Cement 1250kg Jumbo Bag",
    },
    {
      sku: "ACC-PPC-JUMBO-1250",
      hs: "25232990",
      type: "PPC Cement",
      icon: "cement",
      spec: "PPC, 1250kg Jumbo Bag",
      desc: "Bulk jumbo-bag packaging of PPC for large-volume site and RMC batching.",
      name: "ACC PPC Cement 1250kg Jumbo Bag",
    },
    {
      sku: "ACC-WSC-40",
      hs: "25232100",
      type: "White Cement",
      icon: "cement",
      spec: "White Cement, 40kg Bag",
      desc: "High-whiteness cement for decorative work, tile fixing and finishing coats.",
      name: "ACC White Cement 40kg Bag",
    },
    {
      sku: "ACC-WBP-40",
      hs: "38245090",
      type: "Waterproof Plaster",
      icon: "cement",
      spec: "Waterproofing Plaster Compound, 40kg Bag",
      desc: "Ready-mix waterproof plaster compound for damp-resistant internal and external walls.",
      name: "ACC Waterproof Plaster Compound 40kg Bag",
    },
    {
      sku: "ACC-BLOCK-JOINT-40",
      hs: "38245090",
      type: "Block Jointing Mortar",
      icon: "cement",
      spec: "Thin-Bed Block Jointing Mortar, 40kg Bag",
      desc: "Factory-mixed mortar for thin-joint AAC block and concrete block masonry.",
      name: "ACC Block Jointing Mortar 40kg Bag",
    },
  ],
  ASTRAL: [
    {
      sku: "AST-WB-TT-101",
      hs: "69101010",
      type: "Wash Basin",
      icon: "basin",
      spec: 'Table Top, White, 20" x 16"',
      desc: "Vitreous china table-top basin with a glazed, stain-resistant finish.",
      name: "Astral Wash Basin Table Top 20x16 White",
    },
    {
      sku: "AST-WB-WM-104",
      hs: "69101010",
      type: "Wash Basin",
      icon: "basin",
      spec: 'Wall Mounted, White, 22" x 15"',
      desc: "Wall-hung basin with concealed fixing and a slim, space-saving profile.",
      name: "Astral Wash Basin Wall Mounted 22x15 White",
    },
    {
      sku: "AST-SH-RN-208",
      hs: "84818090",
      type: "Shower System",
      icon: "shower",
      spec: 'Overhead Rain Shower, 8" Round, Chrome',
      desc: "Wide-coverage rain shower head with a rub-clean silicone nozzle face.",
      name: "Astral Rain Shower 8 Inch Round Chrome",
    },
    {
      sku: "AST-SH-HH-212",
      hs: "84818090",
      type: "Shower System",
      icon: "shower",
      spec: "Hand Shower with 1.5m Hose, Multi-Flow",
      desc: "Multi-function hand shower with a flexible braided hose and wall hook.",
      name: "Astral Hand Shower Multi-Flow with Hose",
    },
    {
      sku: "AST-MX-BSN-305",
      hs: "84818090",
      type: "Basin Mixer",
      icon: "faucet",
      spec: "Single Lever, Chrome",
      desc: "Ceramic disc cartridge mixer for smooth, drip-free single-lever control.",
      name: "Astral Single Lever Basin Mixer Chrome",
    },
    {
      sku: "AST-MX-BS-309",
      hs: "84818090",
      type: "Bath & Shower Mixer",
      icon: "faucet",
      spec: "Wall Mounted, Chrome",
      desc: "Wall-mounted diverter mixer for combined bath filler and shower use.",
      name: "Astral Bath & Shower Mixer Wall Mounted",
    },
    {
      sku: "AST-HF-315",
      hs: "84818090",
      type: "Health Faucet",
      icon: "faucet",
      spec: "Chrome, with Wall Hook",
      desc: "Anti-scale nozzle head with a lightweight ergonomic grip and wall hook.",
      name: "Astral Health Faucet Chrome with Hook",
    },
    {
      sku: "AST-WM-3IN1-320",
      hs: "84818090",
      type: "Wall Mixer",
      icon: "faucet",
      spec: "3-in-1, Chrome",
      desc: "Three-way wall mixer for basin, overhead shower and health faucet lines.",
      name: "Astral Wall Mixer 3-in-1 Chrome",
    },
    {
      sku: "AST-PC-330",
      hs: "84818090",
      type: "Pillar Cock",
      icon: "faucet",
      spec: "Chrome, Quarter-Turn",
      desc: "Quarter-turn ceramic cartridge pillar cock built for daily heavy use.",
      name: "Astral Pillar Cock Chrome Quarter-Turn",
    },
    {
      sku: "AST-AV-340",
      hs: "84818090",
      type: "Angle Valve",
      icon: "faucet",
      spec: "Chrome, 15mm",
      desc: "Compact isolation valve for basin and WC connection lines.",
      name: "Astral Angle Valve Chrome 15mm",
    },
    {
      sku: "AST-BC-345",
      hs: "84818090",
      type: "Bib Cock",
      icon: "faucet",
      spec: "Chrome, Long Body",
      desc: "Long-body bib cock with a smooth quarter-turn ceramic disc valve.",
      name: "Astral Bib Cock Chrome Long Body",
    },
    {
      sku: "AST-DIV-350",
      hs: "84818090",
      type: "Diverter",
      icon: "faucet",
      spec: "2-Way, Chrome",
      desc: "Two-way concealed diverter for switching between shower outlets.",
      name: "Astral 2-Way Diverter Chrome",
    },
  ],
  GOVINDA: [
    {
      sku: "GVD-TMT-08-500D",
      hs: "72142000",
      type: "TMT Bar",
      icon: "tmtbar",
      spec: "8mm, Fe500D, 12m Length",
      desc: "Thermo-mechanically treated rebar with a tough outer rim and ductile core.",
      name: "Govinda TMT Bar 8mm Fe500D",
    },
    {
      sku: "GVD-TMT-10-500D",
      hs: "72142000",
      type: "TMT Bar",
      icon: "tmtbar",
      spec: "10mm, Fe500D, 12m Length",
      desc: "Thermo-mechanically treated rebar with a tough outer rim and ductile core.",
      name: "Govinda TMT Bar 10mm Fe500D",
    },
    {
      sku: "GVD-TMT-12-500D",
      hs: "72142000",
      type: "TMT Bar",
      icon: "tmtbar",
      spec: "12mm, Fe500D, 12m Length",
      desc: "Thermo-mechanically treated rebar with a tough outer rim and ductile core.",
      name: "Govinda TMT Bar 12mm Fe500D",
    },
    {
      sku: "GVD-TMT-16-550D",
      hs: "72142000",
      type: "TMT Bar",
      icon: "tmtbar",
      spec: "16mm, Fe550D, 12m Length",
      desc: "Higher-grade rebar for structural members needing greater tensile strength.",
      name: "Govinda TMT Bar 16mm Fe550D",
    },
    {
      sku: "GVD-TMT-20-550D",
      hs: "72142000",
      type: "TMT Bar",
      icon: "tmtbar",
      spec: "20mm, Fe550D, 12m Length",
      desc: "Higher-grade rebar for structural members needing greater tensile strength.",
      name: "Govinda TMT Bar 20mm Fe550D",
    },
    {
      sku: "GVD-TMT-25-500D",
      hs: "72142000",
      type: "TMT Bar",
      icon: "tmtbar",
      spec: "25mm, Fe500D, 12m Length",
      desc: "Thermo-mechanically treated rebar with a tough outer rim and ductile core.",
      name: "Govinda TMT Bar 25mm Fe500D",
    },
    {
      sku: "GVD-TMT-32-500D",
      hs: "72142000",
      type: "TMT Bar",
      icon: "tmtbar",
      spec: "32mm, Fe500D, 12m Length",
      desc: "Heavy-section rebar for foundations, columns and raft slabs.",
      name: "Govinda TMT Bar 32mm Fe500D",
    },
    {
      sku: "GVD-TMT-10-415",
      hs: "72142000",
      type: "TMT Bar",
      icon: "tmtbar",
      spec: "10mm, Fe415, 12m Length",
      desc: "Standard-grade rebar suited to residential slab and lintel work.",
      name: "Govinda TMT Bar 10mm Fe415",
    },
    {
      sku: "GVD-TMT-12-415",
      hs: "72142000",
      type: "TMT Bar",
      icon: "tmtbar",
      spec: "12mm, Fe415, 12m Length",
      desc: "Standard-grade rebar suited to residential slab and lintel work.",
      name: "Govinda TMT Bar 12mm Fe415",
    },
    {
      sku: "GVD-BW-20G",
      hs: "72172090",
      type: "Binding Wire",
      icon: "tmtbar",
      spec: "20 Gauge, 20kg Coil",
      desc: "Soft-annealed binding wire for tying rebar cages on site.",
      name: "Govinda Binding Wire 20 Gauge 20kg Coil",
    },
  ],
  KAKA: [
    {
      sku: "KAKA-SW-2T-60",
      hs: "39259090",
      type: "Sliding Window Profile",
      icon: "pvcprofile",
      spec: "2-Track, 60mm Multi-Chamber",
      desc: "Multi-chamber uPVC profile with reinforced steel for wind-load stability.",
      name: "KAKA Sliding Window Profile 2-Track 60mm",
    },
    {
      sku: "KAKA-SW-3T-60",
      hs: "39259090",
      type: "Sliding Window Profile",
      icon: "pvcprofile",
      spec: "3-Track, 60mm Multi-Chamber",
      desc: "Three-track profile adding a dedicated mesh channel for ventilation.",
      name: "KAKA Sliding Window Profile 3-Track 60mm",
    },
    {
      sku: "KAKA-CW-70",
      hs: "39259090",
      type: "Casement Window Profile",
      icon: "pvcprofile",
      spec: "70mm, Openable Sash",
      desc: "Openable-sash casement profile with weather-sealed gaskets on all sides.",
      name: "KAKA Casement Window Profile 70mm",
    },
    {
      sku: "KAKA-SD-100",
      hs: "39259090",
      type: "Sliding Door Profile",
      icon: "pvcprofile",
      spec: "100mm, 2-Track",
      desc: "Heavy-section sliding door profile for wide openings and daily use.",
      name: "KAKA Sliding Door Profile 100mm 2-Track",
    },
    {
      sku: "KAKA-FD-70",
      hs: "39259090",
      type: "French Door Profile",
      icon: "pvcprofile",
      spec: "70mm, Dual Sash",
      desc: "Dual-sash openable profile built for balcony and patio door openings.",
      name: "KAKA French Door Profile 70mm Dual Sash",
    },
    {
      sku: "KAKA-MM-18",
      hs: "39259090",
      type: "Mosquito Mesh Profile",
      icon: "pvcprofile",
      spec: "18mm Track Insert",
      desc: "Slide-in mesh track profile that pairs with the 2-track and 3-track ranges.",
      name: "KAKA Mosquito Mesh Profile 18mm Insert",
    },
    {
      sku: "KAKA-WPC-DF-30",
      hs: "39259090",
      type: "WPC Door Frame",
      icon: "pvcprofile",
      spec: "30mm Wall Thickness",
      desc: "Wood-polymer composite frame that resists moisture, termites and warping.",
      name: "KAKA WPC Door Frame 30mm",
    },
    {
      sku: "KAKA-HDL-40",
      hs: "39259090",
      type: "Window Handle",
      icon: "pvcprofile",
      spec: "uPVC, Zinc-Alloy Core",
      desc: "Lockable window handle with a zinc-alloy core inside a uPVC housing.",
      name: "KAKA uPVC Window Handle Zinc-Alloy",
    },
    {
      sku: "KAKA-MC-60",
      hs: "39259090",
      type: "Multi-Chamber Profile",
      icon: "pvcprofile",
      spec: "60mm, 5-Chamber",
      desc: "Five-chamber profile section for improved thermal and acoustic insulation.",
      name: "KAKA Multi-Chamber Profile 60mm 5-Chamber",
    },
    {
      sku: "KAKA-CC-SET",
      hs: "39259090",
      type: "Corner Cleat & Fittings",
      icon: "pvcprofile",
      spec: "Fittings Set, per Window",
      desc: "Corner cleats, drainage caps and fixing screws bundled per window unit.",
      name: "KAKA Corner Cleat & Fittings Set",
    },
  ],
};
